- name: install complete system
  hosts: localhost
  tasks:
    - import_tasks: tasks/base.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/wm.yml
    - import_tasks: tasks/multimedia.yml
    - import_tasks: tasks/network.yml
    - import_tasks: tasks/dev.yml
    - import_tasks: tasks/cli.yml
    - import_tasks: tasks/apps.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/sdkman.yml
