- name: install base
  become: true
  pacman:
    name:
      - xorg-xrandr
      - xorg-server
      - xorg-xinit
      - man
      - unzip
      - zip
      - docker
      - curl
      - openssh
      - tar
    state: present
    update_cache: true
