- name: download postman
  get_url:
    url: https://dl.pstmn.io/download/latest/linux64
    dest: /tmp/postman.tar.gz
    mode: '0644'

- name: extract postman
  unarchive:
    src: /tmp/postman.tar.gz
    dest: /opt
    remote_src: yes
  become: true

- name: create symlink to postman
  file:
    src: /opt/Postman/Postman
    dest: /usr/local/bin/postman
    state: link
    force: true
  become: true
