- name: ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
- name: set authorized key from file
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ dest_key }}.pub"
- name: start ssh-agent and add key
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ dest_key }}"
  environment:
    SSH_AUTH_SOCK: /tmp/ssh-agent.sock
  args:
    executable: /bin/bash
